# -*- coding: utf-8 -*-
"""Bank_Loan_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TegQqE_QVqAdqqRulCtQ1DLoibpI202O

# **Bank Loan Analysis Report**

### **Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings   # warnings in structured form without cluttering
import plotly.express as px  #  used to create interactive adv charts like tree & heat maps, scatter plots, area charts

df = pd.read_excel("/content/financial_loan_data_excel.xlsx")

df.head()

df.tail()

"""### **Meta Data of Data**"""

print("No. of Rows:", df.shape[0])    # , -> gives space before that number, [0] -> specifically gives number of only rows

print("No. of Columns:", df.shape[1])

df.info

df.dtypes

df.describe()

"""##**KPIs**

### Total Loan Applications
"""

total_loan_application = df['id'].count()
print("Total Loan Applications:", total_loan_application)

"""### Month to Date (MTD) Total Loan Applications"""

# to find this we need total number of applications for latest month, but the data here is historical, so we need to filter out the max(current) year and the month

latest_issue_date = df['issue_date'].max()    # latest date
latest_year = latest_issue_date.year          # with help of latest date we will get latest year
latest_month = latest_issue_date.month

# only filter data from issue_date column that is equal to latest_year, latest_month

mtd_data = df[(df['issue_date'].dt.year == latest_year)& (df['issue_date'].dt.month == latest_month)]  # df['issue_date'].dt.year -> extracting year from issue_date

mtd_loan_applications = mtd_data['id'].count()

print(f"MTD loan applications (for {latest_issue_date.strftime('%B %Y')} ): {mtd_loan_applications}")       # latest_issue_date.strftime('%B %Y') -> formats the datetime

"""### Total Funded Amount"""

total_funded_amount = df['loan_amount'].sum()
total_funded_amount_millions = total_funded_amount/1000000
print("Total Funded Amount: ${:.2f}M".format(total_funded_amount_millions))

"""### Month to Date (MTD) Total Funded Amount"""

latest_issue_date = df['issue_date'].max()    # latest date
latest_year = latest_issue_date.year          # with help of latest date we will get latest year
latest_month = latest_issue_date.month

# only filter data from issue_date column that is equal to latest_year, latest_month

mtd_data = df[(df['issue_date'].dt.year == latest_year)& (df['issue_date'].dt.month == latest_month)]  # df['issue_date'].dt.year -> extracting year from issue_date

mtd_total_funded_amount = mtd_data['loan_amount'].sum()

mtd_total_funded_amount_millions = mtd_total_funded_amount/1000000

print("MTD Total Funded Amount: ${:.2f}M".format(mtd_total_funded_amount_millions))

"""### Total Amount Recieved"""

total_amount_recieved = df['total_payment'].sum()
total_amount_recieved_millions = total_amount_recieved/1000000
print("Total Amount Recieved: ${:.2f}M".format(total_amount_recieved_millions))

"""### MTD Total Amount Recieved"""

latest_issue_date = df['issue_date'].max()    # latest date
latest_year = latest_issue_date.year          # with help of latest date we will get latest year
latest_month = latest_issue_date.month

# only filter data from issue_date column that is equal to latest_year, latest_month

mtd_data = df[(df['issue_date'].dt.year == latest_year)& (df['issue_date'].dt.month == latest_month)]  # df['issue_date'].dt.year -> extracting year from issue_date

mtd_total_amount_recieved = mtd_data['total_payment'].sum()

mtd_total_amount_recieved_millions = mtd_total_amount_recieved/1000000

print("MTD Total Amount Received: ${:.2f}M".format(mtd_total_amount_recieved_millions))

"""### Average Interest Rate"""

average_interest_rate = df['int_rate'].mean()*100
print("Average Interest Rate: {:.2f}%".format(average_interest_rate))

"""### Average Debt-to-Income Ratio (DTI)"""

average_DTI = df['dti'].mean()*100
print("Average Debt-to-Income Ratio (DTI): {:.2f}%".format(average_DTI))

"""### Good Loan Metrics"""

good_loans = df[df['loan_status'].isin(["Fully Paid","Current"])]   # identifying good loans

total_loan_applications = df['id'].count()

good_loan_applications = good_loans['id'].count()

good_loan_funded_amount = good_loans['loan_amount'].sum()

good_loan_recieved = good_loans['total_payment'].sum()


good_loan_funded_amount_millions = good_loan_funded_amount/1000000

good_loan_recieved_millions = good_loan_recieved/1000000

good_loan_percentage = (good_loan_applications/total_loan_applications)*100

print("Good Loan Applications:", good_loan_applications)
print("Good Loan Funded Amount in Millions: ${:.2f}M".format(good_loan_funded_amount_millions))
print("Good Loan Received in Millions: ${:.2f}M".format(good_loan_recieved_millions))
print("Good Loan Percentage: {:.2f}%".format(good_loan_percentage))

"""### Bad Loan Metrics"""

bad_loans = df[df['loan_status'].isin(["Charged Off"])]

total_loan_applications = df['id'].count()

bad_loan_applications = bad_loans['id'].count()

bad_loan_funded_amount = bad_loans['loan_amount'].sum()

bad_loan_recieved = bad_loans['total_payment'].sum()


bad_loan_funded_amount_millions = bad_loan_funded_amount/1000000

bad_loan_recieved_millions = bad_loan_recieved/1000000

bad_loan_percentage = (bad_loan_applications/total_loan_applications)*100

print("Bad Loan Applications:", bad_loan_applications)
print("Bad Loan Funded Amount in Millions: ${:.2f}M".format(bad_loan_funded_amount_millions))
print("Bad Loan Received in Millions: ${:.2f}M".format(bad_loan_recieved_millions))
print("Bad Loan Percentage: {:.2f}%".format(bad_loan_percentage))

"""### Monthly Trends by Issue Date for Total Funded Amount"""

# 1st we will create a variable(monthly_funded) to prepare/store data

# as we want monthly trends, so we need to extract the month from issue date
monthly_funded = ( df.sort_values('issue_date')     # we need chronological order of the months from Jan to Dec; sorts our original DataFrame chronologically.
                     .assign(month_name=lambda x: x['issue_date'].dt.strftime('%b %Y'))   # cfreating a new column for months. dt.strftime -> converting date format to %b as month %Y as 4 digit year
                     .groupby('month_name', sort=False)['loan_amount']      # sort=False -> To keep the sorting same as we did here sort_values('issue_date') orlese it will create new sot based on month name column
                                                                            # ['loan_amount']  -> the value we want in front of month name is funded amount
                     .sum()       # while grouping we always have to mention by what aggregation we want to group it
                     .div(1000000) # want values in millions
                     .reset_index(name = 'loan_amount_millions')      # turns the grouped Series back into a DataFrame with two columns: month_name, loan_amount_millions
                                                                       # turns the index (month_name) back into a column and names the summed column loan_amount_millions
                 )


# now that data has been created we will plot this data

plt.figure(figsize=(10,5))
plt.fill_between(monthly_funded['month_name'], monthly_funded['loan_amount_millions'], color='pink', alpha=0.5)      # alpha=0.5 -> color transparency of particular color
plt.plot(monthly_funded['month_name'], monthly_funded['loan_amount_millions'], linewidth=2, color='blue')   # ploting the line on the chart

# adding lables to the line chart

for i, row in monthly_funded.iterrows():        # The for loop adds a value label above each point in our line chart
    plt.text(
        i,                                      # x-position (point index), i is the integer position of the point on the x-axis (our xticks later map these to month names)
        row['loan_amount_millions'] + 0.1,      # y-position (slightly above the point)
        f"{row['loan_amount_millions']:.2f}",   # label text, formatted to 2 decimals
        ha='center', va='bottom',
        fontsize=9, rotation=0, color='black'
    )

plt.title('Total Funded Amount by Month', fontsize=14)
plt.xlabel('Month')
plt.ylabel('Funded Amount ($ Millions)')
plt.xticks(ticks=range(len(monthly_funded)), labels=monthly_funded['month_name'], rotation=45)      # ticks=range(len(monthly_funded)) -> places ticks at positions 0, 1, 2, ... up to the number of rows in monthly_funded
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""### Monthly Trends by Issue Date for Total Amount Recieved"""

# as we want monthly trends, so we need to extract the month from issue date
monthly_recieved = ( df.sort_values('issue_date')     # we need chronological order of the months from Jan to Dec
                     .assign(month_name=lambda x: x['issue_date'].dt.strftime('%b %Y'))   # for creating a new column for months; dt.strftime -> converting date format to %b as month %Y as 4 digit year
                     .groupby('month_name', sort=False)['total_payment']      # sort=False -> To keep the sorting same as we did here sort_values('issue_date') orlese it will create new sot based on month name column
                                                                            # ['loan_amount']  -> the value we want in front of month name is funded amount
                     .sum()       # while grouping we always have to mention by what aggregation we want to group it
                     .div(1000000) # want values in millions
                     .reset_index(name = 'loan_payment_millions')          # new name given to column that's created by summing, div the loan_amount values

                 )

# now that data has been created we will plot this data

plt.figure(figsize=(10,5))
plt.fill_between(monthly_recieved['month_name'], monthly_recieved['loan_payment_millions'], color='lightyellow', alpha=0.5)      # alpha=0.5 -> color transparency of particular color
plt.plot(monthly_recieved['month_name'], monthly_recieved['loan_payment_millions'], linewidth=2, color='green')   # ploting the line on the chart

# adding lables to the line chart

for i, row in monthly_recieved.iterrows():        # The for loop adds a value label above each point in our line chart
    plt.text(
        i,                                      # x-position (point index), i is the integer position of the point on the x-axis (our xticks later map these to month names)
        row['loan_payment_millions'] + 0.1,      # y-position (slightly above the point)
        f"{row['loan_payment_millions']:.2f}",   # label text, formatted to 2 decimals
        ha='center', va='bottom',
        fontsize=9, rotation=0, color='black'
    )

plt.title('Total Payment Amount by Month', fontsize=14)
plt.xlabel('Month')
plt.ylabel('Payment Amount ($ Millions)')
plt.xticks(ticks=range(len(monthly_recieved)), labels = monthly_recieved['month_name'], rotation=45)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""### Monthly Trends by Issue Date for Total Loan Applications"""

monthly_applications = ( df.sort_values('issue_date')     # we need chronological order of the months from Jan to Dec
                     .assign(month_name=lambda x: x['issue_date'].dt.strftime('%b %Y'))   # for creating a new column for months; dt.strftime -> converting date format to %b as month %Y as 4 digit year
                     .groupby('month_name', sort=False)['id']      # sort=False -> To keep the sorting same as we did here sort_values('issue_date') orlese it will create new sot based on month name column
                                                                            # ['id']  -> the value we want in front of month name is funded amount
                     .count()       # while grouping we always have to mention by what aggregation we want to group it

                     .reset_index(name = 'loan_applications_count')          # new name given to column that's created by summing, div the loan_amount values

                 )

# now that data has been created we will plot this data

plt.figure(figsize=(10,5))
plt.fill_between(monthly_applications['month_name'], monthly_applications['loan_applications_count'], color='skyblue', alpha=0.5)      # alpha=0.5 -> color transparency of particular color
plt.plot(monthly_applications['month_name'], monthly_applications['loan_applications_count'], linewidth=2, color='orange')   # ploting the line on the chart

# adding lables to the line chart

for i, row in monthly_applications.iterrows():        # The for loop adds a value label above each point in our line chart
    plt.text(
        i,                                      # x-position (point index), i is the integer position of the point on the x-axis (our xticks later map these to month names)
        row['loan_applications_count'] + 0.5,      # y-position (slightly above the point)
        f"{row['loan_applications_count']}",   # label text, formatted to 2 decimals
        ha='center', va='bottom',
        fontsize=9, rotation=0, color='black'
    )

plt.title('Total Loan Applications by Month', fontsize=14)
plt.xlabel('Month')
plt.ylabel('Number of Applications')
plt.xticks(ticks=range(len(monthly_applications)), labels = monthly_applications['month_name'], rotation=45)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""Regional Analysis By State for Total Funded Amount"""

# here there is no need to create a new column



regional_funding = df.groupby('address_state')['loan_amount'].sum().sort_values(ascending=True)       # sort_values(ascending=True) -> to display values from highest to lowest on horizontal bars

regional_funding_thousands = regional_funding/1000



# now that data has been created we will plot this data

plt.figure(figsize=(10,8))
bars = plt.barh(regional_funding_thousands.index, regional_funding_thousands.values, color = 'lightcoral')    # barh is for horizontal bars

# adding lables

for bar in bars:
    width = bar.get_width()
    plt.text(width + 10, bar.get_y() + bar.get_height()/2, f'{width:,.0f}K', va='center', fontsize = 9)


plt.title('Total Funded Amount by State (in $ Thousands)')
plt.xlabel('State')
plt.ylabel('Funded Amount ($ Thousands)')
plt.tight_layout()
plt.show()

"""### Loan Term Analysis by Total Amount Recieved"""

loan_term = df.groupby('term')['total_payment'].sum()/1000000


plt.figure(figsize=(5,5))
plt.pie(loan_term, labels = loan_term.index,
        autopct=lambda p: f"{p:.1f}%\n${p*sum(loan_term)/100:.1f}M",      # to convert the amount into millions
        startangle=90,
        wedgeprops = {'width': 0.4}
        )

plt.gca().add_artist(plt.Circle((0,0), 0.70, color='white'))      # this is to add the inner circle for donut shape
plt.title('Total Recieved Amount by Term (in $ Millions)')
plt.show()

"""### Employee Length for Total Loan Applications"""

employment_duration = df.groupby('emp_length')['id'].count().sort_values(ascending=True)       # sort_values(ascending=True) -> to display values from highest to lowest on horizontal bars


# now that data has been created we will plot this data

plt.figure(figsize=(10,7))
bars = plt.barh(employment_duration.index, employment_duration.values, color = 'purple')    # barh is for horizontal bars

# adding lables

for bar in bars:
    width = bar.get_width()
    plt.text(width + 5, bar.get_y() + bar.get_height()/2, f'{width:,.0f}', va='center', fontsize = 9)


plt.title('Employee Length for Total Loan Applications')
plt.ylabel('Employment Length')
plt.xlabel('Number of Applications')
plt.grid(axis = 'x', linestyle = '--', alpha = 0.5)
plt.tight_layout()
plt.show()

"""### Loan Purpose by Total Funded Amount"""

purpose_funding_millions = (df.groupby('purpose')['loan_amount'].sum().sort_values()/1000000)

plt.figure(figsize =(10,6))

bars = plt.barh(purpose_funding_millions.index, purpose_funding_millions.values, color = 'lightgreen')

for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.1, bar.get_y() + bar.get_height()/2, f'{width:.2f}M', va='center', fontsize = 9)


plt.title('Loan Purpose by Total Funded Amount ($ in Millions)')
plt.xlabel('Total Funded Amount ($ in Millions)')
plt.ylabel('Loan Purpose')
plt.grid(axis = 'x', linestyle = '--', alpha = 0.5)
plt.tight_layout()
plt.show()

"""### Home Ownership by Total Amount Recieved"""

home_funding = df.groupby('home_ownership')['total_payment'].sum().reset_index()

home_funding['total_payment_millions'] = home_funding['total_payment']/1000000

fig = px.treemap(

    home_funding,
    path = ['home_ownership'],                # each rectangle = one ownership category
    values = 'total_payment_millions',        # area size = total payment (in millions)
    color = 'total_payment_millions',         # color encodes the same metric
    color_continuous_scale = 'RdBu',
    title = 'Home Ownership by Total Amount Recieved ($ Millions)'
)

fig.show()